# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "Your CLI description"
  homepage "https://docs.miruml.com"
  version "0.3.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/homebrew-cli/releases/download/v0.3.7/cli_Darwin_x86_64.tar.gz"
      sha256 "d23af8f6af6f8ad955d5500a89a780594ff2141eb021a594a49988ef7fb9483b"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/homebrew-cli/releases/download/v0.3.7/cli_Darwin_arm64.tar.gz"
      sha256 "3279ed039929ba70eb698db03c4aba4e2b9f5df4e73edc7bcc9e6a1981b74da1"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/homebrew-cli/releases/download/v0.3.7/cli_Linux_x86_64.tar.gz"
        sha256 "8cf024c3db6d3814729e4530849f710931c29ba088e2fcb4670fddfa97d4343a"

        def install
          bin.install "miru"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/homebrew-cli/releases/download/v0.3.7/cli_Linux_arm64.tar.gz"
        sha256 "7244bb61744ec0085137a5783f6eb5358093c6264e0b05573e45c5c726ddf721"

        def install
          bin.install "miru"
        end
      end
    end
  end
end
