# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "Your CLI description"
  homepage "https://docs.miruml.com"
  version "0.3.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/homebrew-cli/releases/download/v0.3.8/cli_Darwin_x86_64.tar.gz"
      sha256 "0fa508f5eabdd540ba9350d0d8512da1e0c4e6b596346d09031eea8b1b954daa"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/homebrew-cli/releases/download/v0.3.8/cli_Darwin_arm64.tar.gz"
      sha256 "3f1aef4a430d75388354a153f28f0f831fe6e9316188a4750eb12a4b9178bcf4"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/homebrew-cli/releases/download/v0.3.8/cli_Linux_x86_64.tar.gz"
        sha256 "eeca5fa97a416a554882aa8224c7b93767ea9de0476be011a23c63e1fe8433fa"

        def install
          bin.install "miru"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/homebrew-cli/releases/download/v0.3.8/cli_Linux_arm64.tar.gz"
        sha256 "431ce11f2c1ba433ac1f240733a099780bc2f8f8c7f735abaa397a7e240dcbe7"

        def install
          bin.install "miru"
        end
      end
    end
  end
end
