# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "Your CLI description"
  homepage "https://github.com/miruml/miru-cli"
  version "0.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/cli/releases/download/v0.3.6/cli_Darwin_x86_64.tar.gz"
      sha256 "3fcecc3a1f4979195096601f2a53dfaa3e4ab1f3d22e33ad57142e549b478222"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/cli/releases/download/v0.3.6/cli_Darwin_arm64.tar.gz"
      sha256 "ddfa5a9cf97f05638660e50909fe13c19c160f6d5469cb06886bbb45667fed63"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/cli/releases/download/v0.3.6/cli_Linux_x86_64.tar.gz"
        sha256 "3478e510070f4c954ff160a7d1d928ef162fd6ccb44e5c6adcc56549244d4693"

        def install
          bin.install "miru"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/cli/releases/download/v0.3.6/cli_Linux_arm64.tar.gz"
        sha256 "57ae27569926d4a6db79f5fdaa5d95341e00cfed48967d435c078bd557469442"

        def install
          bin.install "miru"
        end
      end
    end
  end
end
